import React from 'react';

export const COUNTRIES = {
  Afghanistan: 'AF',
  Angola: 'AO',
  Albania: 'AL',
  'United Arab Emirates': 'AE',
  Argentina: 'AR',
  Armenia: 'AM',
  Australia: 'AU',
  Austria: 'AT',
  Azerbaijan: 'AZ',
  Burundi: 'BI',
  Belgium: 'BE',
  Benin: 'BJ',
  'Burkina Faso': 'BF',
  Bangladesh: 'BD',
  Bulgaria: 'BG',
  'Bosnia and Herzegovina': 'BA',
  Belarus: 'BY',
  Belize: 'BZ',
  Bolivia: 'BO',
  Brazil: 'BR',
  'Brunei Darussalam': 'BN',
  Bhutan: 'BT',
  Botswana: 'BW',
  'Central African Republic': 'CF',
  Canada: 'CA',
  Switzerland: 'CH',
  Chile: 'CL',
  China: 'CN',
  "Côte d'Ivoire": 'CI',
  Cameroon: 'CM',
  'Democratic Republic of the Congo': 'CD',
  'Republic of Congo': 'CG',
  Colombia: 'CO',
  'Costa Rica': 'CR',
  Cuba: 'CU',
  'Czech Republic': 'CZ',
  Germany: 'DE',
  Djibouti: 'DJ',
  Denmark: 'DK',
  'Dominican Republic': 'DO',
  Algeria: 'DZ',
  Ecuador: 'EC',
  Egypt: 'EG',
  Eritrea: 'ER',
  Estonia: 'EE',
  Ethiopia: 'ET',
  Finland: 'FI',
  Fiji: 'FJ',
  Gabon: 'GA',
  'United Kingdom': 'GB',
  Georgia: 'GE',
  Ghana: 'GH',
  Guinea: 'GN',
  'The Gambia': 'GM',
  'Guinea-Bissau': 'GW',
  'Equatorial Guinea': 'GQ',
  Greece: 'GR',
  Greenland: 'GL',
  Guatemala: 'GT',
  Guyana: 'GY',
  Honduras: 'HN',
  Croatia: 'HR',
  Haiti: 'HT',
  Hungary: 'HU',
  Indonesia: 'ID',
  India: 'IN',
  Ireland: 'IE',
  Iran: 'IR',
  Iraq: 'IQ',
  Iceland: 'IS',
  Israel: 'IL',
  Italy: 'IT',
  Jamaica: 'JM',
  Jordan: 'JO',
  Japan: 'JP',
  Kazakhstan: 'KZ',
  Kenya: 'KE',
  Kyrgyzstan: 'KG',
  Cambodia: 'KH',
  'Republic of Korea': 'KR',
  Kosovo: 'XK',
  Kuwait: 'KW',
  'Lao PDR': 'LA',
  Lebanon: 'LB',
  Liberia: 'LR',
  Libya: 'LY',
  'Sri Lanka': 'LK',
  Lesotho: 'LS',
  Lithuania: 'LT',
  Luxembourg: 'LU',
  Latvia: 'LV',
  Morocco: 'MA',
  Moldova: 'MD',
  Madagascar: 'MG',
  Mexico: 'MX',
  Macau: 'MC',
  Macedonia: 'MK',
  Mali: 'ML',
  Myanmar: 'MM',
  Montenegro: 'ME',
  Mongolia: 'MN',
  Mozambique: 'MZ',
  Mauritania: 'MR',
  Malawi: 'MW',
  Malaysia: 'MY',
  Namibia: 'NA',
  Niger: 'NE',
  Nigeria: 'NG',
  Nicaragua: 'NI',
  Netherlands: 'NL',
  Norway: 'NO',
  Nepal: 'NP',
  'New Zealand': 'NZ',
  Oman: 'OM',
  Pakistan: 'PK',
  Panama: 'PA',
  Peru: 'PE',
  Philippines: 'PH',
  'Papua New Guinea': 'PG',
  Poland: 'PL',
  'Dem. Rep. Korea': 'KP',
  Portugal: 'PT',
  Paraguay: 'PY',
  Palestine: 'PS',
  Qatar: 'QA',
  Romania: 'RO',
  Russia: 'RU',
  Rwanda: 'RW',
  'Western Sahara': 'EH',
  'Saudi Arabia': 'SA',
  Sudan: 'SD',
  'South Sudan': 'SS',
  Senegal: 'SN',
  'Sierra Leone': 'SL',
  'El Salvador': 'SV',
  Serbia: 'RS',
  Suriname: 'SR',
  Slovakia: 'SK',
  Slovenia: 'SI',
  Sweden: 'SE',
  Swaziland: 'SZ',
  Syria: 'SY',
  Chad: 'TD',
  Togo: 'TG',
  Thailand: 'TH',
  Tajikistan: 'TJ',
  Turkmenistan: 'TM',
  'Timor-Leste': 'TL',
  Tunisia: 'TN',
  Turkey: 'TR',
  Taiwan: 'TW',
  Tanzania: 'TZ',
  Uganda: 'UG',
  Ukraine: 'UA',
  Uruguay: 'UY',
  'United States': 'US',
  Uzbekistan: 'UZ',
  Venezuela: 'VE',
  Vietnam: 'VN',
  Vanuatu: 'VU',
  Yemen: 'YE',
  'South Africa': 'ZA',
  Zambia: 'ZM',
  Zimbabwe: 'ZW',
  Somalia: 'SO',
  France: 'FR',
  Spain: 'ES',
  Aruba: 'AW',
  Anguilla: 'AI',
  Andorra: 'AD',
  'Antigua and Barbuda': 'AG',
  Bahamas: 'BS',
  Bermuda: 'BM',
  Barbados: 'BB',
  Comoros: 'KM',
  'Cape Verde': 'CV',
  'Cayman Islands': 'KY',
  Dominica: 'DM',
  'Falkland Islands': 'FK',
  'Faeroe Islands': 'FO',
  Grenada: 'GD',
  'Hong Kong': 'HK',
  'Saint Kitts and Nevis': 'KN',
  'Saint Lucia': 'LC',
  Liechtenstein: 'LI',
  'Saint Martin (French)': 'MF',
  Maldives: 'MV',
  Malta: 'MT',
  Montserrat: 'MS',
  Mauritius: 'MU',
  'New Caledonia': 'NC',
  Nauru: 'NR',
  'Pitcairn Islands': 'PN',
  'Puerto Rico': 'PR',
  'French Polynesia': 'PF',
  Singapore: 'SG',
  'Solomon Islands': 'SB',
  'São Tomé and Principe': 'ST',
  'Saint Martin (Dutch)': 'SX',
  Seychelles: 'SC',
  'Turks and Caicos Islands': 'TC',
  Tonga: 'TO',
  'Trinidad and Tobago': 'TT',
  'Saint Vincent and the Grenadines': 'VC',
  'British Virgin Islands': 'VG',
  'United States Virgin Islands': 'VI',
  Cyprus: 'CY',
  'Reunion (France)': 'RE',
  'Mayotte (France)': 'YT',
  'Martinique (France)': 'MQ',
  'Guadeloupe (France)': 'GP',
  'Curaco (Netherlands)': 'CW',
  'Canary Islands (Spain)': 'IC',
};

export const CODES = {
  'AF': 'Afghanistan',
  'AO': 'Angola',
  'AL': 'Albania',
  'AE': 'United Arab Emirates',
  'AR': 'Argentina',
  'AM': 'Armenia',
  'AU': 'Australia',
  'AT': 'Austria',
  'AZ': 'Azerbaijan',
  'BI': 'Burundi',
  'BE': 'Belgium',
  'BJ': 'Benin',
  'BF': 'Burkina Faso',
  'BD': 'Bangladesh',
  'BG': 'Bulgaria',
  'BA': 'Bosnia and Herzegovina',
  'BY': 'Belarus',
  'BZ': 'Belize',
  'BO': 'Bolivia',
  'BR': 'Brazil',
  'BN': 'Brunei Darussalam',
  'BT': 'Bhutan',
  'BW': 'Botswana',
  'CF': 'Central African Republic',
  'CA': 'Canada',
  'CH': 'Switzerland',
  'CL': 'Chile',
  'CN': 'China',
  'CI': "Côte d'Ivoire",
  'CM': 'Cameroon',
  'CD': 'Democratic Republic of the Congo',
  'CG': 'Republic of Congo',
  'CO': 'Colombia',
  'CR': 'Costa Rica',
  'CU': 'Cuba',
  'CZ': 'Czech Republic',
  'DE': 'Germany',
  'DJ': 'Djibouti',
  'DK': 'Denmark',
  'DO': 'Dominican Republic',
  'DZ': 'Algeria',
  'EC': 'Ecuador',
  'EG': 'Egypt',
  'ER': 'Eritrea',
  'EE': 'Estonia',
  'ET': 'Ethiopia',
  'FI': 'Finland',
  'FJ': 'Fiji',
  'GA': 'Gabon',
  'GB': 'United Kingdom',
  'GE': 'Georgia',
  'GH': 'Ghana',
  'GN': 'Guinea',
  'GM': 'The Gambia',
  'GW': 'Guinea- Bissau',
  'GQ': 'Equatorial Guinea',
  'GR': 'Greece',
  'GL': 'Greenland',
  'GT': 'Guatemala',
  'GY': 'Guyana',
  'HN': 'Honduras',
  'HR': 'Croatia',
  'HT': 'Haiti',
  'HU': 'Hungary',
  'ID': 'Indonesia',
  'IN': 'India',
  'IE': 'Ireland',
  'IR': 'Iran',
  'IQ': 'Iraq',
  'IS': 'Iceland',
  'IL': 'Israel',
  'IT': 'Italy',
  'JM': 'Jamaica',
  'JO': 'Jordan',
  'JP': 'Japan',
  'KZ': 'Kazakhstan',
  'KE': 'Kenya',
  'KG': 'Kyrgyzstan',
  'KH': 'Cambodia',
  'KR': 'Republic of Korea',
  'XK': 'Kosovo',
  'KW': 'Kuwait',
  'LA': 'Lao PDR',
  'LB': 'Lebanon',
  'LR': 'Liberia',
  'LY': 'Libya',
  'LK': 'Sri Lanka',
  'LS': 'Lesotho',
  'LT': 'Lithuania',
  'LU': 'Luxembourg',
  'LV': 'Latvia',
  'MA': 'Morocco',
  'MD': 'Moldova',
  'MG': 'Madagascar',
  'MX': 'Mexico',
  'MC': 'Macau',
  'MK': 'Macedonia',
  'ML': 'Mali',
  'MM': 'Myanmar',
  'ME': 'Montenegro',
  'MN': 'Mongolia',
  'MZ': 'Mozambique',
  'MR': 'Mauritania',
  'MW': 'Malawi',
  'MY': 'Malaysia',
  'NA': 'Namibia',
  'NE': 'Niger',
  'NG': 'Nigeria',
  'NI': 'Nicaragua',
  'NL': 'Netherlands',
  'NO': 'Norway',
  'NP': 'Nepal',
  'NZ': 'New Zealand',
  'OM': 'Oman',
  'PK': 'Pakistan',
  'PA': 'Panama',
  'PE': 'Peru',
  'PH': 'Philippines',
  'PG': 'Papua New Guinea',
  'PL': 'Poland',
  'KP': 'Dem.Rep.Korea',
  'PT': 'Portugal',
  'PY': 'Paraguay',
  'PS': 'Palestine',
  'QA': 'Qatar',
  'RO': 'Romania',
  'RU': 'Russia',
  'RW': 'Rwanda',
  'EH': 'Western Sahara',
  'SA': 'Saudi Arabia',
  'SD': 'Sudan',
  'SS': 'South Sudan',
  'SN': 'Senegal',
  'SL': 'Sierra Leone',
  'SV': 'El Salvador',
  'RS': 'Serbia',
  'SR': 'Suriname',
  'SK': 'Slovakia',
  'SI': 'Slovenia',
  'SE': 'Sweden',
  'SZ': 'Swaziland',
  'SY': 'Syria',
  'TD': 'Chad',
  'TG': 'Togo',
  'TH': 'Thailand',
  'TJ': 'Tajikistan',
  'TM': 'Turkmenistan',
  'TL': 'Timor - Leste',
  'TN': 'Tunisia',
  'TR': 'Turkey',
  'TW': 'Taiwan',
  'TZ': 'Tanzania',
  'UG': 'Uganda',
  'UA': 'Ukraine',
  'UY': 'Uruguay',
  'US': 'United States',
  'UZ': 'Uzbekistan',
  'VE': 'Venezuela',
  'VN': 'Vietnam',
  'VU': 'Vanuatu',
  'YE': 'Yemen',
  'ZA': 'South Africa',
  'ZM': 'Zambia',
  'ZW': 'Zimbabwe',
  'SO': 'Somalia',
  'FR': 'France',
  'ES': 'Spain',
  'AW': 'Aruba',
  'AI': 'Anguilla',
  'AD': 'Andorra',
  'AG': 'Antigua and Barbuda',
  'BS': 'Bahamas',
  'BM': 'Bermuda',
  'BB': 'Barbados',
  'KM': 'Comoros',
  'CV': 'Cape Verde',
  'KY': 'Cayman Islands',
  'DM': 'Dominica',
  'FK': 'Falkland Islands',
  'FO': 'Faeroe Islands',
  'GD': 'Grenada',
  'HK': 'Hong Kong',
  'KN': 'Saint Kitts and Nevis',
  'LC': 'Saint Lucia',
  'LI': 'Liechtenstein',
  'MF': 'Saint Martin(French)',
  'MV': 'Maldives',
  'MT': 'Malta',
  'MS': 'Montserrat',
  'MU': 'Mauritius',
  'NC': 'New Caledonia',
  'NR': 'Nauru',
  'PN': 'Pitcairn Islands',
  'PR': 'Puerto Rico',
  'PF': 'French Polynesia',
  'SG': 'Singapore',
  'SB': 'Solomon Islands',
  'ST': 'São Tomé and Principe',
  'SX': 'Saint Martin(Dutch)',
  'SC': 'Seychelles',
  'TC': 'Turks and Caicos Islands',
  'TO': 'Tonga',
  'TT': 'Trinidad and Tobago',
  'VC': 'Saint Vincent and the Grenadines',
  'VG': 'British Virgin Islands',
  'VI': 'United States Virgin Islands',
  'CY': 'Cyprus',
  'RE': 'Reunion(France)',
  'YT': 'Mayotte(France)',
  'MQ': 'Martinique(France)',
  'GP': 'Guadeloupe(France)',
  'CW': 'Curaco(Netherlands)',
  'IC': 'Canary Islands(Spain)',
};

export const STATUSES = [
  'Visited',
  'Planned',
  'Lived',
  'TODO',
]


const legend = fill => (<svg width="30" height="30">
  <rect width="30" height="30" fill={fill} />
</svg>);

export const LEGEND = {
  TODO: {
    id: 'TODO',
    name: 'TODO',
    description: "I'll get there on day!",
    fill: '#273E47',
    legend,
  },
  Visited: {
    id: 'visited',
    name: 'Visited',
    description: "Countries I've been to (no transfers)",
    fill: '#D8973C',
    legend,
  },
  Planned: {
    id: 'planned',
    name: 'Planned',
    description: "It's been booked and I'm going... soon",
    fill: 'url(#stroke)',
    legend: () => (<svg width="30" height="30">
      <defs>
        <pattern id="stroke" patternUnits="userSpaceOnUse" width="15" height="15" patternTransform="rotate(45)">
          <line x1="0" y="0" x2="0" y2="15" stroke="#A4243B" strokeWidth="28" />
        </pattern>
      </defs>
      <rect width="30" height="30" fill="url(#stroke)" />
    </svg>),
  },
  Lived: {
    id: 'lived',
    name: 'Lived',
    description: "Places I've lived",
    fill: '#226F54',
    legend,
  },
};
